In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv('./data/sample_submission.csv')
data

        Customer_ID  Best_Offer
0      Customer_708           1
1       Customer_47           1
2     Customer_3995           1
3     Customer_1513           1
4     Customer_3686           1
...             ...         ...
2736  Customer_4271           1
2737  Customer_7923           1
2738  Customer_5633           1
2739  Customer_8432           1
2740   Customer_681           1

[2741 rows x 2 columns]

In [5]:
data = pd.read_csv('./data/train.csv')
data

,Customer_ID,Sex,Earnings,Region_Code,Marital Status,State_of_Origin,Customer_Worth,Customer_Reply,Plan,Certification,...,Vehicle Class,Vehicle Size,Months Since Last Claim,Months Since Policy Inception,Counts_of_Open_Complaints,No_Of_POlicy,kind_of_policy,Active_Policy,Sales Channel,Best_Offer
0,Customer_434,Female,97134,Suburban,Single,Kano,5017.009472,Interested,Silver,First_Degree,...,SUV,Medsize,12,15,0,1,Corporate,C_L2,Agent,1
1,Customer_4641,Female,53754,Suburban,Married,Abuja,5151.301306,Not_interested,Silver,First_Degree,...,SUV,Small,5,2,0,1,Personal,P_L2,Agent,3
2,Customer_4952,Female,25804,Suburban,Divorced,Lagos,4906.894731,Interested,Silver,HND,...,Sports Car,Medsize,3,51,0,1,Personal,P_L3,Agent,0
3,Customer_1489,Female,0,Suburban,Single,Imo,8512.525936,Not_interested,Silver,HND,...,Sports Car,Medsize,5,94,0,8,Personal,P_L2,Branch,1
4,Customer_812,Male,140494,Rural,Single,Imo,3280.531880,Not_interested,Silver,PHD,...,Four-Door Car,Medsize,13,19,2,1,Personal,P_L2,Call Center,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6388,Customer_5734,Female,175914,Suburban,Divorced,Lagos,7336.328083,Not_interested,Bronze,HND,...,Four-Door Car,Small,31,63,0,2,Personal,P_L3,Agent,2
6389,Customer_5191,Male,45040,Suburban,Married,Lagos,5500.940679,Interested,Bronze,HND,...,Four-Door Car,Medsize,17,64,0,3,Personal,P_L3,Branch,0
6390,Customer_5390,Female,0,Suburban,Single,Lagos,8994.779137,Not_interested,Silver,O_Level,...,SUV,Medsize,13,4,0,7,Personal,P_L1,Call Center,0
6391,Customer_860,Female,0,Suburban,Divorced,Imo,14637.451580,Interested,Silver,First_Degree,...,SUV,Medsize,5,56,0,2,Personal,P_L3,Call Center,0
6392,Customer_7270,Male,156184,Urban,Married,Imo,3351.639274,Not_interested,Silver,First_Degree,...,Four-Door Car,Medsize,34,13,0,1,Corporate,C_L2,Branch,1

In [6]:
data = pd.read_csv('./data/test.csv')
data

,Customer_ID,Sex,Earnings,Region_Code,Marital Status,State_of_Origin,Customer_Worth,Customer_Reply,Plan,Certification,...,Total Claim Amount,Vehicle Class,Vehicle Size,Months Since Last Claim,Months Since Policy Inception,Counts_of_Open_Complaints,No_Of_POlicy,kind_of_policy,Active_Policy,Sales Channel
0,Customer_708,Male,149170,Rural,Married,Lagos,4224.631209,Not_interested,Bronze,O_Level,...,218.598065,SUV,Medsize,1,49,0,1,Personal,P_L3,Agent
1,Customer_47,Female,46436,Suburban,Single,Abuja,5516.344018,Not_interested,Bronze,O_Level,...,447.793440,Two-Door Car,Medsize,7,10,0,4,Personal,P_L2,Agent
2,Customer_3995,Female,189806,Suburban,Married,Abuja,3810.122147,Interested,Silver,HND,...,451.200000,Two-Door Car,Small,3,38,0,1,Personal,P_L3,Agent
3,Customer_1513,Female,154306,Urban,Married,Lagos,7916.823110,Not_interested,Silver,HND,...,355.641958,Four-Door Car,Medsize,3,27,2,5,Personal,P_L3,Branch
4,Customer_3686,Female,47538,Suburban,Divorced,Kano,7933.722181,Not_interested,Bronze,O_Level,...,470.097411,Four-Door Car,Medsize,18,14,0,2,Personal,P_L2,Branch
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2736,Customer_4271,Male,172192,Suburban,Married,Abuja,4337.353131,Not_interested,Gold,O_Level,...,518.400000,Two-Door Car,Large,30,1,0,1,Corporate,C_L3,Call Center
2737,Customer_7923,Female,0,Suburban,Single,Kano,9033.214859,Interested,Silver,Second_Degree,...,650.521790,Sports Car,Medsize,15,47,0,9,Corporate,C_L2,Branch
2738,Customer_5633,Female,171218,Suburban,Married,Imo,5524.524223,Not_interested,Silver,PHD,...,652.800000,SUV,Medsize,22,17,0,1,Personal,P_L3,Agent
2739,Customer_8432,Male,0,Rural,Married,Abuja,5095.479191,Not_interested,Bronze,O_Level,...,150.878447,Two-Door Car,Large,12,55,0,3,Personal,P_L3,Call Center
2740,Customer_681,Male,70592,Urban,Single,Imo,29196.366390,Not_interested,Silver,Second_Degree,...,452.616872,SUV,Medsize,19,11,0,2,Personal,P_L1,Branch